site_name: EDAM MCP Server
site_description: MCP server for EDAM ontology mapping and concept suggestion
site_author: EDAM MCP Team
site_url: https://edamontology.github.io/edammcp

repo_name: edammcp
repo_url: https://github.com/edamontology/edammcp
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [../edam_mcp]
          options:
            show_source: true
            show_root_heading: true
            show_category_heading: true
            show_signature_annotations: true
            show_bases: true
            heading_level: 2
            members_order: source
            docstring_style: google
            preload_modules: true
  - mkdocs-jupyter:
      include_source: true

markdown_extensions:
  - admonition
  - codehilite
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/edamontology/edammcp

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Configuration: getting-started/configuration.md
  - Developer Guide:
    - Architecture: developer/architecture.md
    - API Reference: developer/api.md
    - Models: developer/models.md
    - Tools: developer/tools.md
    - Ontology: developer/ontology.md
    - Utilities: developer/utils.md
  - Examples:
    - Basic Usage: examples/basic-usage.md
    - Advanced Usage: examples/advanced-usage.md
    - MCP Integration: examples/mcp-integration.md
  - Contributing:
    - Development Setup: contributing/development-setup.md
    - Adding Tools: contributing/adding-tools.md
    - Testing: contributing/testing.md
    - Code Style: contributing/code-style.md 